aliyun:
  oss:
    endpoint: http://oss-cn-hangzhou.aliyuncs.com
    accessKeyId: yourAccessKeyId
    accessKeySecret: yourAccessKeySecret
    bucketName: yourBucketName
mybatis:
  type-aliases-package: edu.scau.mis.pos.domain