server:
  port: 8081

spring:
  devtools:
    restart:
      enabled: true
  datasource:
    # 连接池hikari
    type: com.zaxxer.hikari.HikariDataSource
    # 驱动程序
    driverClassName: com.mysql.cj.jdbc.Driver
    # 连接参数
    url: jdbc:mysql://localhost:3306/isdp-db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: '123'

#mybatis配置
mybatis:
  typeAliasesPackage: edu.scau.mis.pos.domain
  mapperLocations: classpath*:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    # 使用枚举的 name() 值与数据库字符串互转
    # 例如 ProductStatus.active ↔ 数据库里的 'active'
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler

#阿里云oss配置
aliyun:
  oss:
    endpoint: http://oss-cn-hangzhou.aliyuncs.com
    accessKeyId: yourAccessKeyId
    accessKeySecret: yourAccessKeySecret
    bucketName: yourBucketName